DROP TABLE IF EXISTS logs;
DROP TABLE IF EXISTS reservations;
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS flights;
DROP TABLE IF EXISTS airports;
DROP TABLE IF EXISTS seats;
DROP TABLE IF EXISTS type_seat;
DROP TABLE IF EXISTS planes;
DROP TABLE IF EXISTS models;
DROP TABLE IF EXISTS pilots;
DROP TABLE IF EXISTS admins;
DROP TABLE IF EXISTS companies;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
   id_user SMALLINT UNSIGNED AUTO_INCREMENT,
   firstname VARCHAR(32) NOT NULL,
   lastname VARCHAR(32) NOT NULL,
   email VARCHAR(64) NOT NULL,
   password VARCHAR(1024) NOT NULL,
   phone VARCHAR(16) NOT NULL,
   birthday DATE NOT NULL,
   address VARCHAR(64) NOT NULL,
   postal_code VARCHAR(32) NOT NULL,
   country VARCHAR(32) NOT NULL,
   creation_date DATETIME NOT NULL,
   PRIMARY KEY(id_user),
   UNIQUE(email)
)ENGINE = InnoDB;

CREATE TABLE companies(
   id_company SMALLINT UNSIGNED AUTO_INCREMENT,
   name VARCHAR(32) NOT NULL,
   logo VARCHAR(64) NOT NULL,
   PRIMARY KEY(id_company),
   UNIQUE(name)
)ENGINE = InnoDB;

CREATE TABLE logs(
   id_log BIGINT UNSIGNED AUTO_INCREMENT,
   name VARCHAR(64) NOT NULL,
   log VARCHAR(512) NOT NULL,
   category VARCHAR(32) NOT NULL,
   action VARCHAR(32) NOT NULL,
   ip VARCHAR(64) NOT NULL,
   creation_date DATETIME NOT NULL,
   id_user SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY(id_log),
   FOREIGN KEY(id_user) REFERENCES users(id_user)
)ENGINE = InnoDB;

CREATE TABLE admins(
   id_admin SMALLINT UNSIGNED AUTO_INCREMENT,
   id_company SMALLINT UNSIGNED NOT NULL,
   id_user SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY(id_admin),
   UNIQUE(id_user),
   FOREIGN KEY(id_company) REFERENCES companies(id_company),
   FOREIGN KEY(id_user) REFERENCES users(id_user)
)ENGINE = InnoDB;

CREATE TABLE airports(
   id_airport SMALLINT UNSIGNED AUTO_INCREMENT,
   name VARCHAR(64) NOT NULL,
   country VARCHAR(32) NOT NULL,
   PRIMARY KEY(id_airport),
   UNIQUE(name)
)ENGINE = InnoDB;

CREATE TABLE type_seat(
   id_seats SMALLINT UNSIGNED AUTO_INCREMENT,
   name VARCHAR(32) NOT NULL,
   price SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY(id_seats),
   UNIQUE(name)
)ENGINE = InnoDB;

CREATE TABLE models(
   id_model SMALLINT UNSIGNED AUTO_INCREMENT,
   name VARCHAR(32) NOT NULL,
   constructor VARCHAR(32) NOT NULL,
   PRIMARY KEY(id_model),
   UNIQUE(name)
)ENGINE = InnoDB;

CREATE TABLE seats(
   id_seat VARCHAR(16),
   id_model SMALLINT UNSIGNED NOT NULL,
   id_seats SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY(id_seat),
   FOREIGN KEY(id_model) REFERENCES models(id_model),
   FOREIGN KEY(id_seats) REFERENCES type_seat(id_seats)
)ENGINE = InnoDB;

CREATE TABLE pilots(
   id_pilot SMALLINT UNSIGNED AUTO_INCREMENT,
   salary SMALLINT UNSIGNED NOT NULL,
   start_date DATE NOT NULL,
   id_company SMALLINT UNSIGNED NOT NULL,
   id_user SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY(id_pilot),
   UNIQUE(id_user),
   FOREIGN KEY(id_company) REFERENCES companies(id_company),
   FOREIGN KEY(id_user) REFERENCES users(id_user)
)ENGINE = InnoDB;

CREATE TABLE planes(
   id_plane SMALLINT UNSIGNED AUTO_INCREMENT,
   circulation_date DATE NOT NULL,
   id_model SMALLINT UNSIGNED NOT NULL,
   id_company SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY(id_plane),
   FOREIGN KEY(id_model) REFERENCES models(id_model),
   FOREIGN KEY(id_company) REFERENCES companies(id_company)
)ENGINE = InnoDB;

CREATE TABLE flights(
   id_flight INT UNSIGNED AUTO_INCREMENT,
   date_departure DATETIME NOT NULL,
   date_arrival DATETIME NOT NULL,
   avaible_seats SMALLINT UNSIGNED NOT NULL,
   airport_departure SMALLINT UNSIGNED NOT NULL,
   airport_arrival SMALLINT UNSIGNED NOT NULL,
   id_plane SMALLINT UNSIGNED NOT NULL,
   id_pilot SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY(id_flight),
   FOREIGN KEY(airport_departure) REFERENCES airports(id_airport),
   FOREIGN KEY(airport_arrival) REFERENCES airports(id_airport),
   FOREIGN KEY(id_plane) REFERENCES planes(id_plane),
   FOREIGN KEY(id_pilot) REFERENCES pilots(id_pilot)
)ENGINE = InnoDB;

CREATE TABLE tickets(
   id_ticket BIGINT UNSIGNED,
   id_seat VARCHAR(16) NOT NULL,
   id_flight INT UNSIGNED NOT NULL,
   PRIMARY KEY(id_ticket),
   FOREIGN KEY(id_seat) REFERENCES seats(id_seat),
   FOREIGN KEY(id_flight) REFERENCES flights(id_flight)
)ENGINE = InnoDB;

CREATE TABLE reservations(
   id_reservation INT UNSIGNED AUTO_INCREMENT,
   reservation_date DATETIME NOT NULL,
   id_seat VARCHAR(16) NOT NULL,
   id_flight INT UNSIGNED NOT NULL,
   id_user SMALLINT UNSIGNED NOT NULL,
   PRIMARY KEY(id_reservation),
   FOREIGN KEY(id_seat) REFERENCES seats(id_seat),
   FOREIGN KEY(id_flight) REFERENCES flights(id_flight),
   FOREIGN KEY(id_user) REFERENCES users(id_user)
)ENGINE = InnoDB;

INSERT INTO airports (name,country) VALUES
('Durban King Shaka Airport','Afrique du Sud'),
('Port Elizabeth Airport','Afrique du Sud'),
('Tirana Airport','Albanie'),
('Alger Houari Boumédiène Airport','Algérie'),
('Oran Ahmed Ben Bella Airport','Algérie'),
('Allgäu Airport Memmingen','Allemagne'),
('Berlin Brandebourg Airport','Allemagne'),
('Brême Airport','Allemagne'),
('Cologne Bonn Airport','Allemagne'),
('Dortmund Airport','Allemagne'),
('Dresde Airport','Allemagne'),
('Düsseldorf Airport','Allemagne'),
('Francfort Airport','Allemagne'),
('Francfort-Hahn Airport','Allemagne'),
('Friedrichshafen Airport','Allemagne'),
('Hambourg Airport','Allemagne'),
('Hanovre Airport','Allemagne'),
('Karlsruhe Baden-Baden Airport','Allemagne'),
('Leipzig Halle Airport','Allemagne'),
('Munich Airport','Allemagne'),
('Münster Osnabrück Airport','Allemagne'),
('Nuremberg Airport','Allemagne'),
('Paderborn Lippstadt Airport','Allemagne'),
('Stuttgart Airport','Allemagne'),
('Weeze Airport','Allemagne'),
('Buenos Aires Jorge Newbery Airport','Argentine'),
('Buenos Aires Ministro Pistarini Airport','Argentine'),
('Erevan Zvartnots Airport','Arménie'),
('Graz Airport','Autriche'),
('Innsbruck Airport','Autriche'),
('Klagenfurt Airport','Autriche'),
('Linz Airport','Autriche'),
('Salzbourg Airport','Autriche'),
('Vienne Airport','Autriche'),
('Bakou Airport','Azerbaïdjan'),
('Anvers Airport','Belgique'),
('Bruxelles Airport','Belgique'),
('Charleroi Airport','Belgique'),
('Liège Airport','Belgique'),
('Ostende Bruges Airport','Belgique'),
('Minsk Airport','Biélorussie'),
('Sarajevo Airport','Bosnie-Herzégovine'),
('Tuzla Airport','Bosnie-Herzégovine'),
('Bourgas Airport','Bulgarie'),
('Sofia Airport','Bulgarie'),
('Varna Airport','Bulgarie'),
('Hong Kong Airport','Chine'),
('Pékin Capital Airport','Chine'),
('Taiwan Taoyuan Airport','Chine'),
('Larnaca Airport','Chypre'),
('Paphos Airport','Chypre'),
('Dubrovnik Airport','Croatie'),
('Pula Airport','Croatie'),
('Rijeka Krk Airport','Croatie'),
('Split Airport','Croatie'),
('Zadar Airport','Croatie'),
('Zagreb Airport','Croatie'),
('Aalborg Airport','Danemark'),
('Aarhus Airport','Danemark'),
('Billund Airport','Danemark'),
('Copenhague Airport','Danemark'),
('Vágar Airport','Danemark'),
('Alexandrie Borg El Arab Airport','Égypte'),
('Charm el-Cheikh Airport','Égypte'),
('Hurghada Airport','Égypte'),
('Le Caire Airport','Égypte'),
('Abu Dhabi International Airport','Émirats Arabes Unis'),
('Alicante Airport','Espagne'),
('Almeria Airport','Espagne'),
('Asturies Airport','Espagne'),
('Barcelone Airport','Espagne'),
('Bilbao Airport','Espagne'),
('Fuerteventura Airport','Espagne'),
('Gérone Airport','Espagne'),
('Grande Canarie Airport','Espagne'),
('Grenade-Jaén Airport','Espagne'),
('Ibiza Airport','Espagne'),
('Jerez Airport','Espagne'),
('La Palma Airport','Espagne'),
('Lanzarote Airport','Espagne'),
('Madrid Barajas Airport','Espagne'),
('Malaga Airport','Espagne'),
('Minorque Airport','Espagne'),
('Palma de Majorque Airport','Espagne'),
('Región de Murcie Airport','Espagne'),
('Reus Airport','Espagne'),
('Saint-Jacques-de-Compostelle Airport','Espagne'),
('Santander Airport','Espagne'),
('Saragosse Airport','Espagne'),
('Séville Airport','Espagne'),
('Tenerife Nord Airport','Espagne'),
('Tenerife Sud Airport','Espagne'),
('Valence Airport','Espagne'),
('Tallinn Airport','Estonie'),
('Helsinki Airport','Finlande'),
('Oulu Airport','Finlande'),
('Rovaniemi Airport','Finlande'),
('Tampere Airport','Finlande'),
('Turku Airport','Finlande'),
('Vaasa Airport','Finlande'),
('Ajaccio Airport','France'),
('Bastia Airport','France'),
('Bergerac Airport','France'),
('Biarritz Airport','France'),
('Bordeaux Airport','France'),
('Brest Bretagne Airport','France'),
('Figari Sud Corse Airport','France'),
('Lille Airport','France'),
('Lyon-Saint Exupéry Airport','France'),
('Marseille Airport','France'),
('Montpellier Airport','France'),
('Nantes Airport','France'),
('Nice Airport','France'),
('Paris Beauvais Airport','France'),
('Paris Charles de Gaulle Airport','France'),
('Paris Orly Airport','France'),
('Rennes Bretagne Airport','France'),
('Réunion Roland Garros Airport','France'),
('Strasbourg Airport','France'),
('Toulon-Hyères Airport','France'),
('Toulouse Blagnac Airport','France'),
('Tbilissi Airport','Géorgie'),
('Aktion Airport','Grèce'),
('Athènes Airport','Grèce'),
('Chania Airport','Grèce'),
('Corfou Airport','Grèce'),
('Héraklion Airport','Grèce'),
('Kos Airport','Grèce'),
('Lesbos Mytilène Airport','Grèce'),
('Mykonos Airport','Grèce'),
('Rhodes Airport','Grèce'),
('Santorin Airport','Grèce'),
('Thessalonique Airport','Grèce'),
('Zante Airport','Grèce'),
('Budapest Airport','Hongrie'),
('Debrecen Airport','Hongrie'),
('Cork Airport','Irlande'),
('Dublin Airport','Irlande'),
('Irlande Ouest Airport Knock','Irlande'),
('Kerry Airport','Irlande'),
('Shannon Airport','Irlande'),
('Keflavik Airport','Islande'),
('Eilat Ramon Airport','Israël'),
('Tel Aviv Ben Gourion Airport','Israël'),
('Alghero Airport','Italie'),
('Ancône Airport','Italie'),
('Bari Airport','Italie'),
('Bergame Airport','Italie'),
('Bologne Airport','Italie'),
('Brindisi Airport','Italie'),
('Cagliari Airport','Italie'),
('Catane Fontanarossa Airport','Italie'),
('Comiso Airport','Italie'),
('Florence Airport','Italie'),
('Gênes Airport','Italie'),
('Lamezia Terme Airport','Italie'),
('Milan Linate Airport','Italie'),
('Milan Malpensa Airport','Italie'),
('Naples Airport','Italie'),
('Olbia Costa Smeralda Airport','Italie'),
('Palerme Airport','Italie'),
('Pérouse Airport','Italie'),
('Pescara Airport','Italie'),
('Pise Airport','Italie'),
('Rome Ciampino Airport','Italie'),
('Rome Fiumicino Airport','Italie'),
('Trapani Airport','Italie'),
('Trévise Airport','Italie'),
('Trieste Airport','Italie'),
('Turin Airport','Italie'),
('Venise Airport','Italie'),
('Vérone Airport','Italie'),
('Almaty Airport','Kazakhstan'),
('Nursultan Nazarbayev Airport','Kazakhstan'),
('Nairobi Jomo Kenyatta Airport','Kenya'),
('Pristina Airport','Kosovo'),
('Riga Airport','Lettonie'),
('Kaunas Airport','Lituanie'),
('Vilnius Airport','Lituanie'),
('Luxembourg Airport','Luxembourg'),
('Skopje Airport','Macédoine du Nord'),
('Kuala Lumpur Airport','Malaisie'),
('Malte Airport','Malte'),
('Mexico City Airport','Mexique'),
('Chisinau Airport','Moldavie'),
('Podgorica Airport','Monténégro'),
('Tivat Airport','Monténégro'),
('Ålesund Airport','Norvège'),
('Bergen Airport','Norvège'),
('Bodø Airport','Norvège'),
('Haugesund Airport','Norvège'),
('Kristiansand Airport','Norvège'),
('Oslo Airport','Norvège'),
('Sandefjord Airport Torp','Norvège'),
('Stavanger Airport','Norvège'),
('Tromsø Airport','Norvège'),
('Trondheim Airport','Norvège'),
('Amsterdam Airport Schiphol','Pays-Bas'),
('Eindhoven Airport','Pays-Bas'),
('Groningen Airport Eelde','Pays-Bas'),
('Maastricht Aachen Airport','Pays-Bas'),
('Rotterdam La Haye Airport','Pays-Bas'),
('Cracovie Airport','Pologne'),
('Gdansk Airport','Pologne'),
('Katowice Airport','Pologne'),
('Poznan Airport','Pologne'),
('Szczecin-Goleniów Airport','Pologne'),
('Varsovie Airport','Pologne'),
('Varsovie Modlin Airport','Pologne'),
('Wroclaw Airport','Pologne'),
('Faro Airport','Portugal'),
('Lisbonne Airport','Portugal'),
('Madère Airport','Portugal'),
('Ponta Delgada Airport','Portugal'),
('Porto Airport','Portugal'),
('Brno Airport','République tchèque'),
('Prague Airport','République tchèque'),
('Bucarest Henri Coanda Airport','Roumanie'),
('Cluj-Napoca Airport','Roumanie'),
('Iasi Airport','Roumanie'),
('Timisoara Airport','Roumanie'),
('Aberdeen Airport','Royaume-Uni'),
('Belfast City Airport','Royaume-Uni'),
('Belfast International Airport','Royaume-Uni'),
('Birmingham Airport','Royaume-Uni'),
('Bristol Airport','Royaume-Uni'),
('Cardiff Airport','Royaume-Uni'),
('East Midlands Airport','Royaume-Uni'),
('Édimbourg Airport','Royaume-Uni'),
('Exeter Airport','Royaume-Uni'),
('Glasgow Airport','Royaume-Uni'),
('Glasgow Prestwick Airport','Royaume-Uni'),
('Jersey Airport','Royaume-Uni'),
('Leeds Bradford Airport','Royaume-Uni'),
('Liverpool Airport','Royaume-Uni'),
('Londres City Airport','Royaume-Uni'),
('Londres Gatwick Airport','Royaume-Uni'),
('Londres Heathrow Airport','Royaume-Uni'),
('Londres Luton Airport','Royaume-Uni'),
('Londres Southend Airport','Royaume-Uni'),
('Londres Stansted Airport','Royaume-Uni'),
('Manchester Airport','Royaume-Uni'),
('Newcastle Airport','Royaume-Uni'),
('Southampton Airport','Royaume-Uni'),
('Ekaterinbourg Koltsovo Airport','Russie'),
('Krasnodar Airport','Russie'),
('Moscou Cheremetievo Airport','Russie'),
('Moscou Domodedovo Airport','Russie'),
('Moscou Vnoukovo Airport','Russie'),
('Novossibirsk Tolmachevo Airport','Russie'),
('Saint-Pétersbourg Pulkovo Airport','Russie'),
('Sotchi Airport','Russie'),
('Belgrade Nikola Tesla Airport','Serbie'),
('Niš Airport','Serbie'),
('Bratislava Airport','Slovaquie'),
('Košice Airport','Slovaquie'),
('Ljubljana Airport','Slovénie'),
('Göteborg Landvetter Airport','Suède'),
('Malmö Airport','Suède'),
('Stockholm Arlanda Airport','Suède'),
('Stockholm Bromma Airport','Suède'),
('Stockholm Skavsta Airport','Suède'),
('Bâle Mulhouse Fribourg Airport','Suisse'),
('Genève Airport','Suisse'),
('Zurich Airport','Suisse'),
('Bangkok Don Mueang Airport','Thaïlande'),
('Bangkok Suvarnabhumi Airport','Thaïlande'),
('Chiang Mai Airport','Thaïlande'),
('Krabi Airport','Thaïlande'),
('Phuket Airport','Thaïlande'),
('Djerba Airport','Tunisie'),
('Enfidha-Hammamet Airport','Tunisie'),
('Monastir Airport','Tunisie'),
('Tunis-Carthage Airport','Tunisie'),
('Adana Airport','Turquie'),
('Ankara Esenboga Airport','Turquie'),
('Antalya Airport','Turquie'),
('Dalaman Airport','Turquie'),
('Istanbul Airport','Turquie'),
('Istanbul Sabiha Gökcen Airport','Turquie'),
('Izmir Adnan Menderes Airport','Turquie'),
('Milas-Bodrum Airport','Turquie'),
('Trabzon Airport','Turquie'),
('Kharkiv Airport','Ukraine'),
('Kiev Boryspil Airport','Ukraine'),
('Kiev Zhuliany Airport','Ukraine'),
('Lviv Airport','Ukraine'),
('Odessa Airport','Ukraine'),
('Montevideo Carrasco Airport','Uruguay');

INSERT INTO companies (name, logo) VALUES
('Qatar Airways','Qatar_Airways.jpg'),
('United Airlines','United_Airlines.jpg'),
('Qantas','Qantas.jpg'),
('Etihad Airways','Etihad_Airways.jpg'),
('LATAM Airlines','LATAM_Airlines.jpg'),
('Eurowings','Eurowings.jpg'),
('China Airlines','China_Airlines.jpg'),
('American Airlines','American_Airlines.jpg'),
('Japan Airlines (JAL)','Japan_Airlines_(JAL).jpg'),
('Austrian Airlines','Austrian_Airlines.jpg'),
('airBaltic','airBaltic.jpg'),
('LOT Polish Airlines','LOT_Polish_Airlines.jpg'),
('Emirates','Emirates.jpg'),
('All Nippon Airways','All_Nippon_Airways.jpg'),
('Garuda Indonesia','Garuda_Indonesia.jpg'),
('ITA Airways','ITA_Airways.jpg'),
('Air France','Air_France.jpg'),
('Aeromexico','Aeromexico.jpg'),
('Delta Air Lines','Delta_Air_Lines.jpg'),
('KLM Royal Dutch Airlines','KLM_Royal_Dutch_Airlines.jpg'),
('Air Malta','Air_Malta.jpg'),
('Singapore Airlines','Singapore_Airlines.jpg'),
('SAS Scandinavian Airlines','SAS_Scandinavian_Airlines.jpg'),
('Avianca','Avianca.jpg'),
('Brussels Airlines','Brussels_Airlines.jpg'),
('Transavia','Transavia.jpg'),
('Finnair','Finnair.jpg'),
('Swiss International Air Lines','Swiss_International_Air_Lines.jpg'),
('Norwegian','Norwegian.jpg'),
('Westjet','Westjet.jpg'),
('Iberia','Iberia.jpg'),
('Air Tahiti Nui','Air_Tahiti_Nui.jpg'),
('Tap Air Portugal','Tap_Air_Portugal.jpg'),
('Virgin Atlantic','Virgin_Atlantic.jpg'),
('Atlantic Airways','Atlantic_Airways.jpg'),
('Gol','Gol.jpg'),
('Turkish Airlines','Turkish_Airlines.jpg'),
('Aer Lingus','Aer_Lingus.jpg'),
('SunExpress','SunExpress.jpg'),
('Wizz Air','Wizz_Air.jpg'),
('Air Serbia','Air_Serbia.jpg'),
('Condor','Condor.jpg'),
('Air Transat','Air_Transat.jpg'),
('Air Dolomiti','Air_Dolomiti.jpg'),
('Azul Airlines','Azul_Airlines.jpg'),
('Air India','Air_India.jpg'),
('British Airways','British_Airways.jpg'),
('easyJet','easyJet.jpg'),
('Aegean Airlines','Aegean_Airlines.jpg'),
('Jet2.com','Jet2.com.jpg');